// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB34d9UBAoFutZxpJAF-xnlXw6p02DYSRo',
    appId: '1:984722891405:web:75de177e42e1c5ffab38c4',
    messagingSenderId: '984722891405',
    projectId: 'managepersonalfinance-50e9e',
    authDomain: 'managepersonalfinance-50e9e.firebaseapp.com',
    storageBucket: 'managepersonalfinance-50e9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FSegYUnti82ePMOuGXDmMxheKezDdDE',
    appId: '1:984722891405:android:224563aa3c905339ab38c4',
    messagingSenderId: '984722891405',
    projectId: 'managepersonalfinance-50e9e',
    storageBucket: 'managepersonalfinance-50e9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEv5JxpNMWJJBcbs7CRfI4-53sVdxtB6A',
    appId: '1:984722891405:ios:2b61618508bc4a9dab38c4',
    messagingSenderId: '984722891405',
    projectId: 'managepersonalfinance-50e9e',
    storageBucket: 'managepersonalfinance-50e9e.appspot.com',
    iosBundleId: 'com.example.managePersonalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEv5JxpNMWJJBcbs7CRfI4-53sVdxtB6A',
    appId: '1:984722891405:ios:8254d0dc822b0960ab38c4',
    messagingSenderId: '984722891405',
    projectId: 'managepersonalfinance-50e9e',
    storageBucket: 'managepersonalfinance-50e9e.appspot.com',
    iosBundleId: 'com.example.managePersonalFinance.RunnerTests',
  );
}
